import { ObjectType } from "@/types";
import { BellOutlined } from "@ant-design/icons";
import {
  Calendar,
  Home,
  Inbox,
  Search,
  Settings,
  FilePlus,
  UserCheck,
  CircleUser,
  User,
} from "lucide-react";
import { Medication, Notifications } from "@mui/icons-material";

export const SideBarItems = [
  {
    title: "Overview",
    url: "/dashboard",
    icon: Home,
    group: false,
    sideItemTitle: "Dashboard",
    sideItemState: true,
  },
  {
    title: "Appointments",
    url: "/dashboard/appointments",
    icon: Calendar,
    group: true,
    isActive: true,
    items: [
      {
        title: "Month View",
        url: "/dashboard/appointments/#monthview",

      },
      {
        title: "Week View",
        url: "/dashboard/appointments/#weekview",

      },
      {
        title: "Day View",
        url: "/dashboard/appointments/#dayview",

      },
    ],
  },
  {
    title: "Doctors",
    url: "/dashboard/doctors",
    icon: UserCheck,
    private: true,
    group: false,
  },
  {
    title: "Patients",
    url: "/dashboard/patients",
    icon: User,
    group: false,
    sideItemTitle: "patients & nurses",
    sideItemState: true,
  },
  {
    title: "Nurses",
    url: "#",
    icon: User,
    group: false,
  },
  {
    title: "Pharmacy",
    url: "/dashboard/pharmacy",
    icon: Medication,
    group: false,
    sideItemTitle: "Pharmacy",
    sideItemState: true,
  },

  {
    title: "Settings",
    url: "#",
    icon: Settings,
    group: true,
    isActive: true,
    sideItemTitle: "Settings & profile",
    sideItemState: true,

    items: [
      {
        title: "profile",
        url: "/dashboard/settings/profile",
      },
      {
        title: "setting",
        url: "/dashboard/settings/setting",
      },
      {
        title: "code",
        url: "/dashboard/settings/code",
        private: true,
      },
    ],
  },
  {
    title: "metrics",
    url: "#",
    group: true,
    isActive: true,
    sideItemTitle: "Metrics & analytics",
    sideItemState: true,
    icon:TableChart,
    items: [
      {
        title: "API",
        url: "/dashboard/metrics/apiMetrics",
      },
    ],
  },
  {
    title: "notifications",
    url: "/dashboard/notifications",
    icon: Notifications,
    group: false,
    sideItemTitle: "Notification & preferences",
    sideItemState: true,
  },
];

export const AccountSettingMenuItems = [
  {
    title: "profile",
    url: "/dashboard/settings/profile",
  },
  {
    title: "setting",
    url: "/dashboard/settings/setting",
  },
  {
    title: "code",
    url: "/dashboard/settings/code",
    private: true,
  },
];

export const Days = ["Sat", "Sun", "Mon", "Tue", "Wed", "Thu", "Fri"];

export const months = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];

export const medicalSpecialties = [
  "Allergist/Immunologist",
  "Anesthesiologist",
  "Cardiologist",
  "Dermatologist",
  "Emergency Medicine Specialist",
  "Endocrinologist",
  "Gastroenterologist",
  "Geriatrician",
  "Hematologist",
  "Hepatologist",
  "Infectious Disease Specialist",
  "Internist (Internal Medicine)",
  "Nephrologist",
  "Neurologist",
  "Neurosurgeon",
  "Obstetrician/Gynecologist (OB/GYN)",
  "Oncologist",
  "Ophthalmologist",
  "Orthopedic Surgeon",
  "Otolaryngologist (ENT)",
  "Pathologist",
  "Pediatrician",
  "Plastic Surgeon",
  "Psychiatrist",
  "Pulmonologist",
  "Radiologist",
  "Rheumatologist",
  "Surgeon",
  "Sports Medicine Specialist",
  "Urologist",
  "Vascular Surgeon",
  "Interventional Cardiologist",
  "Neonatologist",
  "Reproductive Endocrinologist",
  "Pain Management Specialist",
  "Palliative Care Specialist",
  "Medical Geneticist",
  "Sleep Medicine Specialist",
];

export const weights = [
  "50 kg (110.23 lbs)",
  "55 kg (121.25 lbs)",
  "60 kg (132.28 lbs)",
  "65 kg (143.3 lbs)",
  "70 kg (154.32 lbs)",
  "75 kg (165.35 lbs)",
  "80 kg (176.37 lbs)",
  "85 kg (187.39 lbs)",
  "90 kg (198.42 lbs)",
  "95 kg (209.44 lbs)",
  "100 kg (220.46 lbs)",
  "105 kg (231.49 lbs)",
  "110 kg (242.51 lbs)",
  "115 kg (253.53 lbs)",
  "120 kg (264.56 lbs)",
  "125 kg (275.58 lbs)",
  "130 kg (286.6 lbs)",
  "135 kg (297.62 lbs)",
  "140 kg (308.65 lbs)",
  "145 kg (319.67 lbs)",
  "150 kg (330.69 lbs)",
];

export const heights = [
  "150 cm (4 ft 11 in)",
  "155 cm (5 ft 1 in)",
  "160 cm (5 ft 3 in)",
  "165 cm (5 ft 5 in)",
  "170 cm (5 ft 7 in)",
  "175 cm (5 ft 9 in)",
  "180 cm (5 ft 11 in)",
  "185 cm (6 ft 1 in)",
  "190 cm (6 ft 3 in)",
  "195 cm (6 ft 5 in)",
  "200 cm (6 ft 7 in)",
];

export const notificationSounds = (tone: keyof ObjectType): string | null => {
  const systemSounds: ObjectType = {
    adminOnly: {
      title: "public",
      tone: "/assets/audio/airport-call-157168.mp3",
    },
    public: {
      title: "AdminOnly",
      tone: "/assets/audio/appointment.mp3",
    },
  };
  return systemSounds[tone].tone;
};

export const bloodTypes = ["A+", "A-", "B+", "B-", "O+", "O-", "AB+", "AB-"];
export const emergencyContactRelationships = [
  "Spouse",
  "Parent",
  "Sibling",
  "Child",
  "Grandparent",
  "Grandchild",
  "Aunt",
  "Uncle",
  "Cousin",
  "Niece",
  "Nephew",
  "Friend",
  "Guardian",
  "Partner",
  "Colleague",
  "Neighbor",
  "Caregiver",
  "In-Law",
  "Other",
];
export const allergies = {
  food: [
    "Other",
    "Peanuts",
    "Tree Nuts (Almonds, Walnuts, Cashews)",
    "Dairy (Milk, Cheese, Yogurt)",
    "Shellfish (Shrimp, Crab, Lobster)",
    "Eggs",
    "Soy",
    "Wheat (Gluten)",
    "Fish (Salmon, Tuna, Cod)",
  ],
  medicine: [
    "Penicillin",
    "Aspirin",
    "Ibuprofen",
    "Sulfa Drugs",
    "Codeine",
    "Insulin",
    "Antibiotics (Amoxicillin, Cephalosporins)",
  ],
  environmental: [
    "Pollen",
    "Dust Mites",
    "Mold",
    "Animal Dander",
    "Insect Stings (Bees, Wasps)",
    "Latex",
  ],
};

export const medicalConditions: string[] = [
  "Diabetes",
  "Hypertension",
  "Asthma",
  "Heart Disease",
  "Cancer",
  "Chronic Kidney Disease",
  "Liver Disease",
  "Chronic Obstructive Pulmonary Disease (COPD)",
  "Epilepsy",
  "Thyroid Disorders",
  "Arthritis",
  "HIV/AIDS",
  "Tuberculosis",
  "Mental Health Disorders (Depression, Anxiety, Bipolar Disorder, etc.)",
  "Autoimmune Diseases (Lupus, Rheumatoid Arthritis, etc.)",
  "Stroke",
  "Obesity",
  "Gastroesophageal Reflux Disease (GERD)",
  "Anemia",
];

export const genders = [
  "Male",
  "Female",
  "Non-Binary",
  "Genderfluid",
  "Genderqueer",
  "Agender",
  "Bigender",
  "Two-Spirit",
  "Demiboy",
  "Demigirl",
  "Androgynous",
  "Neutrois",
  "Transgender Male",
  "Transgender Female",
  "Intersex",
  "Pangender",
  "Third Gender",
  "Maverique",
  "Polygender",
  "Omnigender",
  "Xenogender",
];

export const Frequencies = ["daily", "occasionally", "rarely", "never"];

export const medicationStrengths = [
  "other",
  "50mg",
  "100mg",
  "150mg",
  "200mg",
  "250mg",
  "300mg",
  "400mg",
  "500mg",
  "600mg",
  "800mg",
  "1000mg",
  "2.5mg",
  "5mg",
  "7.5mg",
  "10mg",
  "12.5mg",
  "20mg",
  "25mg",
  "30mg",
  "35mg",
  "40mg",
  "60mg",
  "75mg",
  "80mg",
  "90mg",
  "120mg",
  "500mcg",
  "750mcg",
  "1mcg",
  "2mcg",
  "5mcg",
  "10mcg",
  "20mcg",
  "50mcg",
  "100mcg",
  "0.5mg",
  "1mg",
  "2mg",
  "15mg",
  "125mg/5ml",
  "250mg/5ml",
  "500mg/5ml",
  "1000mg/5ml",
  "100U/ml",
  "200U/ml",
  "300U/ml",
  "500U/ml",
  "1g",
  "2g",
  "5g",
  "10g",
  "50g",
  "100g",
  "0.5% w/v",
  "1% w/v",
  "2% w/v",
  "5% w/v",
] as const;
export const medicationRoutes = [
  "other",
  "Oral",
  "Intravenous (IV)",
  "Intramuscular (IM)",
  "Subcutaneous (SC)",
  "Inhalation",
  "Topical",
  "Sublingual",
  "Buccal",
  "Rectal",
  "Vaginal",
  "Ophthalmic",
  "Otic",
  "Transdermal",
  "Intranasal",
  "Intradermal",
  "Epidural",
  "Intrathecal",
  "Enteral",
] as const;

export const medicationForms = [
  "other",
  "Tablet",
  "Capsule",
  "Liquid",
  "Syrup",
  "Suspension",
  "Injection",
  "Inhaler",
  "Patch",
  "Cream",
  "Ointment",
  "Gel",
  "Lotion",
  "Suppository",
  "Drops",
  "Powder",
  "Granules",
  "Implant",
  "Spray",
  "Lozenge",
  "Effervescent Tablet",
  "Solution",
  "Emulsion",
] as const;
export const medicationCategories = [
  "other",
  "Analgesic",
  "Antibiotic",
  "Antifungal",
  "Antiviral",
  "Antihypertensive",
  "Antidiabetic",
  "Antidepressant",
  "Antipsychotic",
  "Anticonvulsant",
  "Anticoagulant",
  "Antiplatelet",
  "Beta Blocker",
  "Calcium Channel Blocker",
  "Diuretic",
  "Bronchodilator",
  "Corticosteroid",
  "NSAID",
  "Opioid",
  "Proton Pump Inhibitor",
  "H2 Receptor Antagonist",
  "Antiemetic",
  "Antihistamine",
  "Antiparasitic",
  "Muscle Relaxant",
  "Sedative",
  "Hypnotic",
  "Antineoplastic",
  "Hormone Therapy",
  "Immunosuppressant",
  "Immunomodulator",
  "Lipid-Lowering Agent",
  "Osteoporosis Treatment",
  "Antispasmodic",
  "Thyroid Hormone",
  "Vasodilator",
  "Anticholinergic",
  "Antimigraine",
] as const;




export const firstNumber = ['1'] as const
export const characters = ["C","D","E"] as const
export const FiveNumber = ['1','2','3','4','5'] as const
export const codeExpirationPlans = ["month","3month","6month","1year"] as const


export const Roles = [
  "clear",
  "Admin",
  "Senior Consultant",
  "Resident Doctor",
  "Intern Doctor",
  "Head Secretary",
  "Charge Secretary",
  "Head Nurse",
  "Charge Nurse"
] as const
